# Generated by Django 5.2 on 2025-04-27 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('complexity_level', models.CharField(choices=[('Simple', 'Simple'), ('Moderate', 'Moderate'), ('Difficult', 'Difficult')], default='Simple', max_length=10)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('academic_year', models.PositiveIntegerField()),
                ('financial_status', models.CharField(choices=[('Good', 'Good'), ('Struggling', 'Struggling'), ('Scholarship', 'Scholarship')], default='Good', max_length=15)),
                ('enrollment_status', models.CharField(choices=[('Active', 'Active'), ('Dropped Out', 'Dropped Out'), ('Graduated', 'Graduated')], default='Active', max_length=15)),
                ('gpa', models.FloatField(default=1.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='AttritionAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('certainty_score', models.FloatField(help_text='Certainty percentage between 0 and 100.')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attrition_result', to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.FloatField()),
                ('year', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='app.student')),
            ],
        ),
    ]
